global:
  postgresql:
    auth: 
      postgresPassword: temporal
      username: temporal
      password: temporal
      database: temporal
primary:
  resources:
    requests:
      memory: 1Gi
      cpu: 250m
    limits:
      memory: 4Gi
      cpu: 500m