server:
  replicaCount: 1
  config:
    numHistoryShards: 256
    persistence:
      default:
        driver: "sql"
        sql:
          driver: "postgres12"
          host: postgresql.default.svc.cluster.local
          port: 5432
          database: temporal_persistence
          user: temporal
          password: temporal
          maxConns: 20
          maxIdleConns: 20
          maxConnLifetime: "1h"
      visibility:
        driver: "sql"
        sql:
          driver: "postgres12"
          host: postgresql.default.svc.cluster.local
          port: 5432
          database: temporal_visibility
          user: temporal
          password: temporal
          maxConns: 20
          maxIdleConns: 20
          maxConnLifetime: "1h"
  frontend:
    service:
      type: NodePort
      port: 7233
      targetPort: 7233
      nodePort: 30233

web:
  service:
    type: NodePort
    port: 8080
    targetPort: 8080
    nodePort: 30080

cassandra:
  enabled: false
elasticsearch:
  enabled: false

grafana:
  enabled: true
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
    nodePort: 30000
  adminPassword: temporal
